module.exports = {
    head:{
        link: [
            {
                rel: 'icon',
                type: 'image/png',
                sizes: '16x16',
                href: '/favicon-16x16.png',
            },
            {
                rel: 'icon',
                type: 'image/png',
                sizes: '32x32',
                href: '/favicon-32x32.png',
            },
            {
                rel: 'apple-touch-icon',
                sizes: '180x180',
                href: '/apple-touch-icon.png',
            },
        ],
    },
    generate: {
        routes: [
            '/kiosk/ahmed-islaih',
            '/kiosk/alex-ball',
            '/kiosk/amanda-spilker',
            '/kiosk/andres-marulanda',
            '/kiosk/andrew-park',
            '/kiosk/ben-reimer',
            '/kiosk/blayne-robinson',
            '/kiosk/brendan-ho',
            '/kiosk/briana-santos',
            '/kiosk/caleb-jones',
            '/kiosk/carol-cheung',
            '/kiosk/chantal-lam',
            '/kiosk/chaz-escoffery',
            '/kiosk/cheng-peng',
            '/kiosk/chloe-lu',
            '/kiosk/colin-o-neill',
            '/kiosk/cynthia-yang',
            '/kiosk/daundre-pryce-pierre',
            '/kiosk/dan-sherwin-lizardo',
            '/kiosk/daniel-mestas',
            '/kiosk/demi-peppas',
            '/kiosk/donny-jun-wen',
            '/kiosk/elyse-turton',
            '/kiosk/emma-wootton',
            '/kiosk/harmoney-lee',
            '/kiosk/hiba-ahmed',
            '/kiosk/hubert-si',
            '/kiosk/jagroop-ghuman',
            '/kiosk/jake-aiton',
            '/kiosk/jessica-tran',
            '/kiosk/josh-behrens',
            '/kiosk/josh-millard',
            '/kiosk/jovaughn-rowe',
            '/kiosk/karl-achiles',
            '/kiosk/kaspar-so',
            '/kiosk/katlin-walsh',
            '/kiosk/kiet-bui',
            '/kiosk/kristina-silvester',
            '/kiosk/luca-scarci',
            '/kiosk/luigi-cody-nicastro',
            '/kiosk/matthew-mirski',
            '/kiosk/maya-pisetskaya',
            '/kiosk/meagan-mccomiskey',
            '/kiosk/megan-keith',
            '/kiosk/meghan-rose',
            '/kiosk/michael-valentine',
            '/kiosk/mike-rugo',
            '/kiosk/sarah-pawlett',
            '/kiosk/sean-fitzmartin',
            '/kiosk/sean-ikeno',
            '/kiosk/sebastian-croce',
            '/kiosk/shanil-patel',
            '/kiosk/shashaank-srinivasan',
            '/kiosk/shawn-kadawathage',
            '/kiosk/shivangi-patel',
            '/kiosk/si-on-chung',
            '/kiosk/tomi-sami',
            '/kiosk/trinh-pham',
            '/kiosk/tryston-hoyes',
            '/kiosk/yael-hubert',
            '/kiosk/yiling-chen',
            '/kiosk/zach-sheppard'
        ]
    }
}

